"""Create files table

Revision ID: 86f420f340ed
Revises:
Create Date: 2024-11-23 23:08:20.478415

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86f420f340ed"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=False, comment="File path"),
        sa.Column(
            "original_name",
            sa.String(length=255),
            nullable=False,
            comment="File original name",
        ),
        sa.Column("size", sa.String(), nullable=False, comment="File size in bytes"),
        sa.Column(
            "content_type",
            sa.String(length=255),
            nullable=False,
            comment="File content type",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_files")),
        sa.UniqueConstraint("uuid", name=op.f("uq_files_uuid")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("files")
    # ### end Alembic commands ###
