"""Update comments in files table

Revision ID: e2ed4b2a80e9
Revises: 86f420f340ed
Create Date: 2024-11-25 13:25:55.828803

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e2ed4b2a80e9"
down_revision: Union[str, None] = "86f420f340ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files",
        "path",
        existing_type=sa.VARCHAR(length=255),
        comment="File path in local disk",
        existing_comment="File path",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files",
        "path",
        existing_type=sa.VARCHAR(length=255),
        comment="File path",
        existing_comment="File path in local disk",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
